### ISSUE TITLE
Kurumi boss timing

### ISSUE THREAD

**Issue by makise-homura** [laochailan/taisei#41]
While testing stage functionality, I found that Kurumi (in boss role) timing is a bit strange.

At first, I wasn't able to reach introduction dialog with her - she starts her attacks after nearly 4 seconds of waiting.
It seems to be solved if I change AT(400) to AT(120) in src/stages/stage4_events.c:417 (kurumi_boss_intro()), but I'm not sure that I do it right.

Additionally, last attack of her final spell card (Power Sign ~ Blow the Walls) occurs after the ending dialog starts (and I have to dodge it while first dialog line is displayed).

Reproduced two times with either with Youmu and Marisa. Here goes two replays with this issue (note: they were recorded with "--" commented at src/player.c:212 to achieve some sort of infinite lives).

[replays.zip](https://github.com/laochailan/taisei/files/726664/replays.zip)

**Comment by laochailan** [comment]
Truth be told, even I don’t remember the possible implications of this. I’m just a bit surprised that we didn’t notice this back in the day.

What hat i do remember though, is that we never got replays to be 100% portable, so I’m not sure if it will create the same results for me. But I will test this in a few days.

**Comment by laochailan** [comment]
The dialog indeed didn’t appear. I think changing the AT like you did should do the trick. I pushed that change.

The final attack thing seems to be one of her slaves that create the bullets when they hit the wall surviving. Normally, the functions containing danmaku logic get called with the special negative time argument EVENT_DEATH when an enemy dies or a boss attack is over.

If boss attacks create slaves, it’s their responsibility to clean up so most boss attacks actually contain something like

```
AT(EVENT_DEATH)
  killall(global.enemies);
```

But Blow the Walls didn’t have this. I added it now and haven’t been able to reproduce this anymore. Can you test?

**Comment by makise-homura** [comment]
Thank you for fixes! I will test it this evening (in about four-five hours from now).

**Comment by makise-homura** [comment]
Thanks for the dialog (now it works), but "Blow the walls" issue is still representable (replay is attached
[taisei_20370130_22-28-32_MSK_stg4_youmuA_easy.zip](https://github.com/laochailan/taisei/files/740196/taisei_20370130_22-28-32_MSK_stg4_youmuA_easy.zip)).

As far as I may note, it occurs not at boss death or before it, but even after its death animation was triggered. After a bit of debug, I noticed that one of slaves is still alive after boss_death() has been executed, and looks like this AT(EVENT_DEATH) somehow does not even execute. When I add a debug printf there, as follows:
```
  AT(EVENT_DEATH)
                {killall(global.enemies); printf("%d: death\n",t);}
```
then I never see corresponding message at the console, but debug printfs in other places work normally.
In addition, I see that blowwall_slave() after its creation tries to spawn many projectiles at each frame, and once it succeeds, it destroys itself; so described situation may be reached when boss dies between moments when slave was created, and when it becomes able to spawn projectiles. I think that killing slaves should help this, so looks like there's subject to investigate - why does AT(EVENT_DEATH) not work in this place.

**Comment by laochailan** [comment]
I got suspicious about that, too when I attempted to fix it. Maybe the last card of the boss doesn’t get the EVENT_DEATH call for some reason. it should be but maybe the boss logic gets terminated before that. I’ll look into it. If you want you can check if it works with 
https://github.com/laochailan/taisei/commit/3a45171a02d87676d7550d399981e12658030e3f
in that commit i had added an explicit call to the EVENT_DEATH thing on boss death.

But I’ll investigate it further.

**Comment by makise-homura** [comment]
It didn't help, I think, it's because `(*boss)->current` is already NULL in boss_death() - process_boss() does so, so EVENT_DEATH was never generated at this point. But process_boss() does `boss->current->rule(boss, EVENT_DEATH)` before, so second call (in boss_death()), i think, is not needed.

But! As far as I suspect, `AT(EVENT_DEATH)` does not work there, but if I change it to `if (time == EVENT_DEATH)` it becomes working, as if current boss->rule (which, as I think, is current attack handler) receives EVENT_DEATH as 'time' argument, and TIMER macro sets __timep to t, which is, as I think, EVENT_DEATH % 600 (since there is `int t = time % 600;` and then `TIMER(&t);`). And voila! Now a slave who spawned projectiles after Kurumi's death dies with her and everything after her death is clean - as it should be.

So, summarizing: AT(EVENT_DEATH) checks not the correct time in such cases, but remainder of divisions.
Maybe, in such places, where time set to remainder instead of correct time, every AT(EVENT_DEATH) should be changed to if(time == EVENT_DEATH) or something like this?
Affected functions, where TIMER is initialized by remainder of time, but not time itself: kurumi_slaveburst(), kurumi_redspike(), stage4_supercard(), kurumi_blowwall(), kurumi_danmaku(). They all are in stage4_events.c. Additionally, there is such arithmetic in iku_lightning() (stage5_events.c), but there is correct comparison (time == EVENT_DEATH), as I may expect.

**Comment by laochailan** [comment]
Awesome! Thanks for figuring that out. I didn’t notice it. Yes, it should be replaced everywhere for clearness.
